config/routes.rb
Rails.application.routes.draw do
 
  resources :households
  resources :incidents
  resources :health_records
  resources :users
 	resources :records
	resources :incidents
	resources :me

root to: "pages#index"

get "login", to: "pages#show_login"
post "login", to: "pages#new_login"
get "logout", to: "pages#logout"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/record.rb
class Record < ApplicationRecord
	validates :order, presence:true
	validates :name, presence:true
	validates :phone, presence:true
	validates :email, format: {with: /.*@.*/}
	
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]
	before_action :check_login

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end


  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:name, :phone, :email, :order, :deadline)
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_with(model: record, local: true) do |form| %>
  <% if record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :Record_log %>
    <%= form.text_area :order %>
  </div>

  <div class="field">
    <%= form.label :Date_of_residency %>
    <%= form.datetime_select :deadline %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/records/_list_record.html.erb
<p id="notice"><%= notice %></p>

<h1>Records</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Record Log</th>
      <th>Date of Residency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.name %></td>
        <td><%= record.phone %></td>
        <td><%= record.email %></td>
        <td><%= record.order %></td>
        <td><%= record.deadline %></td>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record', new_record_path %>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<%= render "shared/jumbotron", header: "General Records", tag_line: "" %>


<%= render "list_record", records: @records, header: "Records" %>

app/views/records/new.html.erb
<h1>New Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @record.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @record.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @record.email %>
</p>

<p>
  <strong>Order:</strong>
  <%= @record.order %>
</p>

<p>
  <strong>Date_of_Residency:</strong>
  <%= @record.deadline %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>