config/routes.rb
Rails.application.routes.draw do
 
  resources :households
  resources :incidents
  resources :health_records
  resources :users
 	resources :records
	resources :incidents
	resources :me

root to: "pages#index"

get "login", to: "pages#show_login"
post "login", to: "pages#new_login"
get "logout", to: "pages#logout"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/health_record.rb
class HealthRecord < ApplicationRecord
	
end

app/models/household.rb
class Household < ApplicationRecord
end

app/models/incident.rb
class Incident < ApplicationRecord
end

app/models/incidentt.rb
class Incident < ApplicationRecord
end

app/models/me.rb
class Me < ApplicationRecord
end

app/models/record.rb
class Record < ApplicationRecord
	validates :order, presence:true
	validates :name, presence:true
	validates :phone, presence:true
	validates :email, format: {with: /.*@.*/}
	
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  before_action :set_incident, only: [:show, :edit, :update, :destroy]
before_action :check_login

  # GET /incidents
  # GET /incidents.json
  def index
    @incidents = Incident.all
  end

  # GET /incidents/1
  # GET /incidents/1.json
  def show
  end

  # GET /incidents/new
  def new
    @incident = Incident.new
  end

  # GET /incidents/1/edit
  def edit
  end

  # POST /incidents
  # POST /incidents.json
  def create
    @incident = Incident.new(incident_params)

    respond_to do |format|
      if @incident.save
        format.html { redirect_to @incident, notice: 'Incident was successfully created.' }
        format.json { render :show, status: :created, location: @incident }
      else
        format.html { render :new }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incidents/1
  # PATCH/PUT /incidents/1.json
  def update
    respond_to do |format|
      if @incident.update(incident_params)
        format.html { redirect_to @incident, notice: 'Incident was successfully updated.' }
        format.json { render :show, status: :ok, location: @incident }
      else
        format.html { render :edit }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incidents/1
  # DELETE /incidents/1.json
  def destroy
    @incident.destroy
    respond_to do |format|
      format.html { redirect_to incidents_url, notice: 'Incident was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incident
      @incident = Incident.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incident_params
      params.require(:incident).permit(:address, :reported_by, :phone, :date, :details)
    end
end

app/controllers/incidentss_controller.rb
class IncidentsController < ApplicationController
	def index

	end

	def show_login
	end

	def new_login
		@username = params[:username]
		@password = params[:password]

		@u = User.find_by(username: @username)

		if @u && @u.authenticate(@password) then
		session[:user_info] = @u
		end

		redirect_to "/"
	end

	def logout
		session[:user_info] = nil
		redirect_to "/"
	end

end

app/controllers/me_controller.rb
class MeController < ApplicationController
	def index

	end

	def show_login
	end

	def new_login
		@username = params[:username]
		@password = params[:password]

		@u = User.find_by(username: @username)

		if @u && @u.authenticate(@password) then
		session[:user_info] = @u
		end

		redirect_to "/"
	end

	def logout
		session[:user_info] = nil
		redirect_to "/"
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index

	end

	def show_login
	end

	def new_login
		@username = params[:username]
		@password = params[:password]

		@u = User.find_by(username: @username)

		if @u && @u.authenticate(@password) then
		session[:user_info] = @u
		end

		redirect_to "/"
	end

	def logout
		session[:user_info] = nil
		redirect_to "/"
	end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]
	before_action :check_login

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end


  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:name, :phone, :email, :order, :deadline)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
before_action :check_login

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def check_login
		if session[:user_info].nil? then
			return false
		else
			return true
		end
	end
end

app/helpers/health_records_helper.rb
module HealthRecordsHelper
end

app/helpers/households_helper.rb
module HouseholdsHelper
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/incidentss/_form.html.erb
<%= form_with(model: health_record, local: true) do |form| %>
  <% if health_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(health_record.errors.count, "error") %> prohibited this health_record from being saved:</h2>

      <ul>
      <% health_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday %>
	<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <div class="input-group date" id="datetimepicker4" data-target-input="nearest">
                    <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker4"/>
                    <div class="input-group-append" data-target="#datetimepicker4" data-toggle="datetimepicker">
                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker4').datetimepicker({
                    format: 'L'
                });
            });
        </script>
    </div>
</div>

  </div>

  <div class="field">
    <%= form.label :diagnosis %>
    <%= form.text_area :diagnosis %>
  </div>

  <div class="field">
    <%= form.label :recorded_by %>
    <%= form.text_field :recorded_by %>
  </div>

  <div class="field">
    <%= form.label :history %>
    <%= form.text_area :history %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/incidentss/_list_health_record.html.erb
<p id="notice"><%= notice %></p>

<h1>Health Records</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birthday</th>
      <th>Diagnosis</th>
      <th>Recorded by</th>
      <th>History</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @health_records.each do |health_record| %>
      <tr>
        <td><%= health_record.name %></td>
        <td><%= health_record.birthday %></td>
        <td><%= health_record.diagnosis %></td>
        <td><%= health_record.recorded_by %></td>
        <td><%= health_record.history %></td>
        <td><%= link_to 'Show', health_record %></td>
        <td><%= link_to 'Edit', edit_health_record_path(health_record) %></td>
        <td><%= link_to 'Destroy', health_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Health Record', new_health_record_path %>

app/views/incidentss/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Barangay Huyon-Huyon Database Management Systems</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/records">Records</a>
      </li>

      
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/incidents">Incidents</a>
      </li>

   </li>
      <li class="nav-item">
        <a class="nav-link" href="/health_records">Health Records</a>
      </li>

	<li class="nav-item">


      </li>


    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/incidentss/edit.html.erb
<h1>Editing Health Record</h1>

<%= render 'form', health_record: @health_record %>

<%= link_to 'Show', @health_record %> |
<%= link_to 'Back', health_records_path %>

app/views/incidentss/index.html.erb
<%= render "shared/jumbotron", header: "Incident Reports", tag_line: "" %>

<%= render "list_incidents", records: @incidents, header: "Incident Reports" %>

app/views/incidentss/new.html.erb
<h1>New Health Record</h1>

<%= render 'form', health_record: @health_record %>

<%= link_to 'Back', health_records_path %>

app/views/incidentss/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @health_record.name %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @health_record.birthday %>
</p>

<p>
  <strong>Diagnosis:</strong>
  <%= @health_record.diagnosis %>
</p>

<p>
  <strong>Recorded by:</strong>
  <%= @health_record.recorded_by %>
</p>

<p>
  <strong>History:</strong>
  <%= @health_record.history %>
</p>

<%= link_to 'Edit', edit_health_record_path(@health_record) %> |
<%= link_to 'Back', health_records_path %>