config/routes.rb
Rails.application.routes.draw do
 
  resources :households
  resources :incidents
  resources :health_records
  resources :users
 	resources :records
	resources :incidents
	resources :me

root to: "pages#index"

get "login", to: "pages#show_login"
post "login", to: "pages#new_login"
get "logout", to: "pages#logout"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/household.rb
class Household < ApplicationRecord
end

app/controllers/households_controller.rb
class HouseholdsController < ApplicationController
  before_action :set_household, only: [:show, :edit, :update, :destroy]

  # GET /households
  # GET /households.json
  def index
    @households = Household.all
  end

  # GET /households/1
  # GET /households/1.json
  def show
  end

  # GET /households/new
  def new
    @household = Household.new
  end

  # GET /households/1/edit
  def edit
  end

  # POST /households
  # POST /households.json
  def create
    @household = Household.new(household_params)

    respond_to do |format|
      if @household.save
        format.html { redirect_to @household, notice: 'Household was successfully created.' }
        format.json { render :show, status: :created, location: @household }
      else
        format.html { render :new }
        format.json { render json: @household.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /households/1
  # PATCH/PUT /households/1.json
  def update
    respond_to do |format|
      if @household.update(household_params)
        format.html { redirect_to @household, notice: 'Household was successfully updated.' }
        format.json { render :show, status: :ok, location: @household }
      else
        format.html { render :edit }
        format.json { render json: @household.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /households/1
  # DELETE /households/1.json
  def destroy
    @household.destroy
    respond_to do |format|
      format.html { redirect_to households_url, notice: 'Household was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_household
      @household = Household.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def household_params
      params.require(:household).permit(:name, :address, :phone, :log, :date_of_residency)
    end
end

app/helpers/households_helper.rb
module HouseholdsHelper
end

app/views/households/_form.html.erb
<%= form_with(model: household, local: true) do |form| %>
  <% if household.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(household.errors.count, "error") %> prohibited this household from being saved:</h2>

      <ul>
      <% household.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :log %>
    <%= form.text_area :log %>
  </div>

  <div class="field">
    <%= form.label :date_of_residency %>
    <%= form.date_select :date_of_residency %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/households/_list_household.erb
<p id="notice"><%= notice %></p>

<h1>Households</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Log</th>
      <th>Date of residency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @households.each do |household| %>
      <tr>
        <td><%= household.name %></td>
        <td><%= household.address %></td>
        <td><%= household.phone %></td>
        <td><%= household.log %></td>
        <td><%= household.date_of_residency %></td>
        <td><%= link_to 'Show', household %></td>
        <td><%= link_to 'Edit', edit_household_path(household) %></td>
        <td><%= link_to 'Destroy', household, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Household', new_household_path %>

app/views/households/edit.html.erb
<h1>Editing Household</h1>

<%= render 'form', household: @household %>

<%= link_to 'Show', @household %> |
<%= link_to 'Back', households_path %>

app/views/households/index.html.erb
<%= render "shared/jumbotron", header: "Household Records", tag_line: "" %>


<%= render "list_household", records: @household, header: "Household" %>

app/views/households/new.html.erb
<h1>New Household</h1>

<%= render 'form', household: @household %>

<%= link_to 'Back', households_path %>

app/views/households/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @household.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @household.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @household.phone %>
</p>

<p>
  <strong>Log:</strong>
  <%= @household.log %>
</p>

<p>
  <strong>Date of residency:</strong>
  <%= @household.date_of_residency %>
</p>

<%= link_to 'Edit', edit_household_path(@household) %> |
<%= link_to 'Back', households_path %>